### PR TITLE
Update Chinese_Simplified.xml

### PR DESCRIPTION
**Pull request by Leesace**
Added new translations and refined some translations in previous PRs.

### CODE REVIEW

**Comment by kleuter** [comment]
Thanks, are you sure that the **LetsMoveMac** section is NOT good?

**Comment by Leesace** [comment]
Translations of that section had a different style of addressing the user (in short it's less politeful), compared with other sections. Anyway I can withdraw those if you like.

**Comment by Leesace** [comment]
> Thanks, are you sure that the **LetsMoveMac** section is NOT good?

Translations of that section had a different style of addressing the user (in short it's less politeful), compared with other sections. Anyway I can withdraw those if you like.

**Comment by kleuter** [comment]
If it's more polite, it's great! thank you.

**Pull request merged**
