### PR TITLE
pt-pt updates and corrections

### PR DESCRIPTION
**Pull request by nebeker**
Updated untranslated strings and made several corrections. The word "fan" was consistently misspelled.

### CODE REVIEW

**Comment by kleuter** [comment]
Thanks a lot!

**Comment by nebeker** [comment]
Sure, happy to improve the experience for other Portugueses speakers.

Any chance of getting a license as a perk for my contribution?

**Comment by kleuter** [comment]
Sure, please drop us a line [via email](support@crystalidea.com)

**Comment by nebeker** [comment]
Sure, thanks.

**Pull request merged**
