### PR TITLE
new translation

### PR DESCRIPTION
**Pull request by J-Teijeiro**
Complete Galician translation

### CODE REVIEW

**Comment by kleuter** [comment]
I'm sorry this language cannot be currently supported by the app.

**Comment by J-Teijeiro** [comment]
What's the reason for that?

**Comment by kleuter** [comment]
what flag would be associated with this language?

**Comment by J-Teijeiro** [comment]
The galician flag. It's a white background with a light blue stripe from the top-left corner to the bottom-right corner. The galician language(galego) is the oficial language from Galicia alongside with spanish (like with catalan in Catalonia).
https://en.wikipedia.org/wiki/Galician_language
https://en.wikipedia.org/wiki/Galicia_(Spain)

**Pull request closed without merging**
