### PR TITLE
Update Chinese_Simplified.xml

### PR DESCRIPTION
**Pull request by 1105420698**
Added more translations for Chinese simplified.

### CODE REVIEW

**Comment by 1105420698** [comment]
I do not know if you want to translate "Pro" and "Free" so please check if my addition is what you like.

**Comment by kleuter** [comment]
Thanks!

**Comment by kleuter** [comment]
Many strings are left translated though, unfortunately

**Comment by 1105420698** [comment]
Yeah sorry about that, I didn’t have time to translate all of them, I can do that tonight though.

**Comment by kleuter** [comment]
Please update to the latest version, it's updated.

**Comment by kleuter** [comment]
Only invalidLicenseMismatchOS is left

**Comment by 1105420698** [comment]
Got it

**Pull request merged**
